### ISSUE TITLE
Retry on errors

### ISSUE THREAD

**Issue by azmeuk** [migraf/fhir-kindling#193]
Sometimes FHIR servers returns error codes.
Recently I worked with a server that randomly returns 504 timeout errors. The fact that this happens on one single page from a large batch made me think that this would be nice if fhir-kindling could automatically retry unsuccessful requests.
Maybe a `nb_attempts` parameters on `FhirServer.query` could do the job.
What do you think?

**Comment by migraf** [comment]
Sounds reasonable to me. I think these issues pop up fairly frequently, so establishing this functionality seems like a good idea. Maybe as an optional parameter for the query methods and as an optional property of a  `FhirServer` instance.

I will include this in the 1.0 release which should be out in the next few weeks

**Comment by migraf** [comment]
I just publish `v1.0.0` which includes retry functionality configurable for the `FhirServer` class.

```python
from fhir_kindling import FhirServer

fhir_server = FhirServer(
    api_address="http://fhir.example.com/R4",
    retry_status_codes=[500, 502, 503, 504],            
    retry_backoff_factor=0.5, 
    max_attempts=10, 
    max_backoff_wait=60
)
```

Feel free to try it out

**Comment by azmeuk** [comment]
Hi. Thank you very much for taking care of this :bowing_man: 
I updated and configured my client so it will use the retry options you made.
As I cannot really provoke a failure on the FHIR server to test, I will just wait and see. If something is going wrong I'll open a new ticket, but in the meantime I think we can close this one.
Thank you again for your hard work
