### ISSUE TITLE
`__repr__` on objects

### ISSUE THREAD

**Issue by azmeuk** [migraf/fhir-kindling#55]
After playing a bit with the library I found that objects are lacking custom `repr` strings that would be useful in a test/debugging context. I think displaying the query parameters would be helpful.

For instance a query has this representation:
```python
>>> server.query(resource=Organization).where("identifier", QueryOperators.eq, "http://finess.sante.gouv.fr%7C")
<fhir_kindling.fhir_query.fhir_query.FHIRQuery object at 0x7f3f0df5eaf0>
```

Where I think something like this would be clearer:
```python
<FHIRQuery resource=Organization identifier="http://finess.sante.gouv.fr%7C">
```

What do you think?

**Comment by migraf** [comment]
Totally agree! Small thing that makes it much easier to get a feel for the objects initally

**Comment by azmeuk** [comment]
Since #55 this is a lot better, however now there is a lot of parameters to read, most of them being `None`:

```
<FHIRQuery(resource=resource_type='Organization' fhir_comments=None id=None id__ext=None implicitRules=None implicitRules__ext=None language=None language__ext=None meta=None contained=None extension=None modifierExtension=None text=None active=None active__ext=None address=None alias=None alias__ext=None contact=None endpoint=None identifier=None name=None name__ext=None partOf=None telecom=None type=None, url=http://demo.openfhir.annuaire.asipsante.fr:8080/fhir/Organization?identifier=http://finess.sante.gouv.fr%7C&_count=5000&_format=json>
```

Maybe it worth displaying attributes only if the attributes only if they are not `None`?

**Comment by migraf** [comment]
That was a total mistake on my part, should be fixed now. Only the type of the queried resource is displayed now as well as information about included resources
```
<FHIRQuery(resource=Condition, include=subject, url=http://localhost:9090/fhir/Condition?_include=Condition:subject&_count=5000&_format=json>
```
