### ISSUE TITLE
Clean up the dependencies

### ISSUE THREAD

**Issue by azmeuk** [migraf/fhir-kindling#70]
Hi. fhir-kindling has a lot of dependencies, some of them does not seem necessary at the moment:

https://github.com/migraf/fhir-kindling/blob/b33d215a0f445a76ae3b3bd78eaa8dd713de1059/setup.py#L34-L48

- tqdm is never called in the code
- click is only used [for this unique](https://github.com/migraf/fhir-kindling/blob/0354a2c6f5a959120c23ce6dec7c551e2d16ef34/fhir_kindling/fhir_server/auth.py#L40) `click.echo` call
- pandas is huge, maybe it can be made an [optional dependency](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies) ?
- pendulum is only called a few times for `pendulum.now`

What do you think?

**Comment by migraf** [comment]
Datascience dependencies such as pandas are now separated and only install when you install with the `ds` extra 
```bash
pip install fhir-kindling[ds]
```
