### ISSUE TITLE
Migrate to poetry

### ISSUE THREAD

**Issue by azmeuk** [migraf/fhir-kindling#77]
pipfile seems to be a dead-end as it [did not received commit in years](https://github.com/pypa/pipfile).

I suggest migrating to [poetry](https://github.com/python-poetry/poetry), that has a very active development. I can provide a PR if this is OK with you.

**Comment by migraf** [comment]
I'm using [pipenv](https://github.com/pypa/pipenv) which seems to be sort of the follow up project and is also pretty active. I have though about poetry but to me it seems like it's poetry or nothing as it doesn't seem to allow multiple dependency managers in the same python installation. 

Though I did maybe want to go for poetry in a python 3.10. compatible version.

**Comment by migraf** [comment]
Closed by ee0c3896dfb0adb96ebd5a9367f9fe588da3ca6f
